### ISSUE TITLE
Create Poem Writing page (UI)

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#20]
This page is meant to allow registered users to write and publish their own poem. You could probably use a simple text-area HTML element for that. Oh, you'll also need a text input for an optional title.

For now, you don't need to care about the API or the server side stuff.

**Comment by TomerPacific** [comment]
Hi @raymag , I'd like to help. 
Apart from the UI itself, any other things I should take care of? Should I make sure users are registered and present a dialog if they aren't? Or should the UI be disabled if a user is not registered?

**Comment by raymag** [comment]
Hi @TomerPacific, in the case of this page I think both things should happen. The UI should be disabled and a dialog should appear asking for the user to sign up. 

Now, about how to know if the user is logged or now, you can set a cookie for that.

**Comment by TomerPacific** [comment]
@raymag , got it. I don't have any background using cookies, but I'll keep you updated on what I am going to do.

**Comment by raymag** [comment]
Oh! I made a merge a while ago implementing a login mechanism. So in order to check wheather the user is authenticated or not, check if the item "tk" on [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) is defined. In other words, you can use ```localStorage.getItem("tk")``` for that purpose.

**Comment by TomerPacific** [comment]
@raymag , wanted to update on my progress.
Here is how it looks like:

![chrome_7ahLc1qBOq](https://user-images.githubusercontent.com/23402988/95583788-56c98280-0a45-11eb-823b-68d1515ddfbf.png)

![chrome_SDJ3DemDS6](https://user-images.githubusercontent.com/23402988/95569294-0abf1380-0a2e-11eb-9d48-d5d5723d0e94.png)

You can see that if the user is not logged in, the input and textarea are disabled.

I also wanted to ask, how the user submits the poem? Where is it saved to?

If you have any suggestions or comments, please let me know.

**Comment by raymag** [comment]
@TomerPacific, we're using [this API](https://github.com/raymag/floesia-api) to deal with that. 

For now, our approach is to handle everything with JavaScript. 
In other words, we take the data in the form and send a POST request to [this route](https://floesia-api.herokuapp.com/poems) passing *title* and *body* as body parameters. The route requires authentication, so it's also necessary to set ```x-access-token``` to the authentication token of the client in the headers.

If the user is logged in, this token will be stored in the [local storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) which you can get using ```localStorage.getItem('tk')```.

The poems are all stored in a mongodb database.

Here are some print screens of how you can add new poems using post requests, (I'm using [Insomnia](https://insomnia.rest/) to test the API routes):
![route](https://i.imgur.com/AqI9xFM.png)
![route2](https://i.imgur.com/1C7PL4W.png)

If you have more questions or if I wasn't clear, please tell me. Keep up the good work o/

**Comment by raymag** [comment]
Also, sorry for taking so long to answer. I was kinda busy with some college stuff.

**Comment by TomerPacific** [comment]
@raymag , I've created a [PR](https://github.com/raymag/floesia/pull/72).
Let me know if something is missing or if anything needs to be changed.

Also, can you add the hacktoberfest tag this issue or the hacktoberfest accepted tag to the PR?

**Comment by raymag** [comment]
Cool, I already merged it! Thank you for the contribution!
(I've also added the hacktoberfest label to the PR, so you're fine)

**Comment by TomerPacific** [comment]
@raymag , thank you..
