### ISSUE TITLE
Add Dark Mode system

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#36]
We could add Dark Mode toggles to most pages and use JavaScript to switch between different CSS files. In other words, we need to write a new CSS file for the Dark Mode (which is also a different issue, check #17) and when the toggle is used, the JavaScript will change the href attribute in the <link> tag for the base CSS. Note that, you'll need to add a ID to that specific tag.

**Comment by kunaljain0212** [comment]
@raymag Can I work on this issue, please?

**Comment by raymag** [comment]
Of course!

**Comment by danielochka** [comment]
Can I try to work on this? I'm new here.

**Comment by raymag** [comment]
Well @danielochka, right now, @kunaljain0212  is already assigned to this issue. You guys can work together on this if both of you agree. You can also look for another issue, if you prefer so.

**Comment by danielochka** [comment]
Okay, no prob. I'll find another one ;) Thank you.

**Comment by kunaljain0212** [comment]
@danielochka I am okay with collaborating on it.

**Comment by danielochka** [comment]
I need to ask my teacher, because I need some issue for my school project and I think I must find something I will work on alone. But thank you very much ;)
