### ISSUE TITLE
Fix poems that are floating above the navbar in Feed/Index page

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#37]
In the feed page, the poems are running above the navbar when you scroll down. Naturally, they should be running below that, so a fix is necessary. That can possibly be solved changing the z-index of the navbar using CSS.

**Comment by ARKEOLOGIST** [comment]
Hi, I have made a PR that fixes the issue. Can you please take a look at it?

**Comment by raymag** [comment]
Yes, I just merged it. We thank you for the contribution.
