### ISSUE TITLE
Consume API in Sign up page

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#53]
The API we are developing for Floesia already supports login and sign up. You can find the [API repository here](https://github.com/raymag/floesia-api), you are free to contribute to it as well.

Right now, there is the /signup route that receives 3 arguments (username, email, password) using body parameters and only accepts the POST method. That's all that is needed to create an account. Take note that email and username should be unique.

**Comment by HugoCPinto** [comment]
Can I work on this issue? =]

**Comment by raymag** [comment]
Sure, I'll assign you to it. Feel free to ask questions if you have any doubts.

**Comment by raymag** [comment]
I just merged it, nice job!
