### ISSUE TITLE
Make Feed page (index.html) pull poems from API

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#57]
The API already has methods to deal with getting poems and adding new poems. In other words, it's time for us to link the feed page to the API.

You can find the link to the repository and the link where the API is hosted in the README. In order to get the poems, all you need to do it make a GET request to "/poems" and you'll get some poems. 

Right now I think, the default maximum number of poems per page is 5, so if you don't add ?items=numberthatyouwant to the request you'll likely get a maximum of 5 poems.

**Comment by dfoltynski** [comment]
You can assign me to that 😊

**Comment by dfoltynski** [comment]
@raymag 
done, you can check it

**Comment by raymag** [comment]
Cool! It's already merged.
