### ISSUE TITLE
Create a logout page

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#58]
Basically, all you need to do is remove the "tk" item from the local storage. That will do the trick.

Worry not about adding the logout link through the other pages, we will only implement the logout mechanism for now. Feel free to ask any questions if you have doubts.

**Comment by dfoltynski** [comment]
sooo all I have to do is localstorage.removeItem("tk") and design logout page?

**Comment by raymag** [comment]
That's it. You actually don't need to design the page as well, but you'll need to redirect the client to index.html after removing "tk" from the local storage. This way, when someone click a logout button or link, the token will be removed and that person will be redirected.

Do you want to take the issue?

**Comment by dfoltynski** [comment]
yea, assign me 😊

**Comment by dfoltynski** [comment]
do you have any test credentials? I want to check if i did everything ok

**Comment by raymag** [comment]
I do. You can use this one:
email: floesia@test
password: test

**Comment by dfoltynski** [comment]
thanks for credentials, You can review it 😊

**Comment by raymag** [comment]
I just merged it, nice job!
