### ISSUE TITLE
Adjust dark mode button and logout link on index.html navbar

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#63]
Both the dark mode switch and the logout link are working as it should. The only problem is that they are kinda overlapping each other in the navbar from the Feed page (index.html). 

Moving the dark mode switch to inside the navbar-links section might help solving it. Feel free to ask any questions if you need to.

**Comment by Wendlereis** [comment]
Hey, would like to work on it! Could you assign it to me?

**Comment by raymag** [comment]
Sure!
