### ISSUE TITLE
Add Heart UI button to Poems renderer in Feed page (index.html)

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#70]
We're going to soon add a feature that allows users to "love" or give a "like" to poems they enjoy. So we are going to first build a simple UI for it. All it needs to do is add a simple "heart" button to each poem, respect design basics though. 

Also, add an label/span that shows the number of hearts that poem has received. Use fake numbers for now.  If you have questions, feel free to ask.

**Comment by nermoo** [comment]
i could try if you like🙂

**Comment by raymag** [comment]
That would be very cool, I'm going to assign it to you then.

**Comment by nermoo** [comment]
does this count as a valid hacktoberfest pr

**Comment by raymag** [comment]
Any Pull Request on this repository counts for Hacktoberfest, since the hacktoberfest topic is active in it.

**Comment by akshayitzme** [comment]
Sorry to interrupt. Did you mean like this ?

![added-heart](https://user-images.githubusercontent.com/60477442/95711801-25d59180-0c81-11eb-8a87-64af92257639.png)

**Comment by nermoo** [comment]
> 
> 
> Sorry to interrupt. Did you mean like this ?
> 
> ![added-heart](https://user-images.githubusercontent.com/60477442/95711801-25d59180-0c81-11eb-8a87-64af92257639.png)

hmm it seems like you already completed the task my friend.

**Comment by akshayitzme** [comment]
Yea. I just tried. In the image I did with span and icon. But I guess we need to use a button right ?.

**Comment by akshayitzme** [comment]
i changed it to button ( if you're  having plans to implement like feature.. i guess so. 
styled button color to be transparent to appear not like a button ). 

i saw this issue is already assigned to @nermoo . So Can i create a PR ? if he already worked on it i'm willing to leave it to him 🙂
![added-heart2](https://user-images.githubusercontent.com/60477442/95756805-e54b3780-0cc3-11eb-892e-12c7f9138daa.png)

**Comment by raymag** [comment]
Hi @akshayitzme, if @nermoo  is okay with it you can open the pull request.

**Comment by nermoo** [comment]
> 
> 
> i changed it to button ( if you're having plans to implement like feature.. i guess so.
> styled button color to be transparent to appear not like a button ).
> 
> i saw this issue is already assigned to @nermoo . So Can i create a PR ? if he already worked on it i'm willing to leave it to him 🙂
> ![added-heart2](https://user-images.githubusercontent.com/60477442/95756805-e54b3780-0cc3-11eb-892e-12c7f9138daa.png)

go ahead bro.im totally ok with it.

**Comment by akshayitzme** [comment]
@nermoo Thank you bro 😊. Happy hacking #hacktoberfest
