### ISSUE TITLE
Add login button to NavBar in Feed page (index.html)

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#73]
This is how the feed page is looking when you aren't authenticated:
![feed](https://i.imgur.com/0Cziu7m.png)

Since the user is not authenticated, I think it's a good idea to add a login button to the NavBar. It will be way easier this way. 

By the way, I'd suggest you to use a minimalist white icon or button to it, since it doesn't draws too much attention and also looks good with the navbar color pallet.

**Comment by chernykhal** [comment]
@raymag Heeey, I would like to do this :)

**Comment by raymag** [comment]
I already assigned you to it, have fun! o/

**Comment by raymag** [comment]
Just merged it, thanks for the contribution!
