### ISSUE TITLE
Add loading animation to Feed UI

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#79]
For technical reasons, our [API]() sometimes has a cold start and takes a little bit to return the poems. That can be troublesome since all we got in the mean time is a bunch of weird "boxes" with no content at all. For that purpose, I think we should add some kind of animation that tells the client that the website is "loading" the poems. When the API finally answers, we turn off the animation and go on. 

By the way, take a look at [poems.js](https://github.com/raymag/floesia/blob/main/js/poems.js) as well, it might be helpful.

**Comment by KristianDunne** [comment]
Is this issue available for the public? If so I would like to be assigned to this.

Thanks.

**Comment by raymag** [comment]
Sure, I'm going to do it right now.
