### ISSUE TITLE
add link to addPoems.html in Feed's page navbar 

### ISSUE THREAD

**Issue by raymag** [raymag/floesia#98]
That's how the feed page (index.html) looks when you're logged.

![feed](https://i.imgur.com/LIFySlm.png)

So we should add an button to the [addPoems](https://github.com/raymag/floesia/blob/main/addPoem.html) page if the user is logged. You can write the javascript for it in the [base.js](https://github.com/raymag/floesia/blob/main/js/base.js) file.

**Comment by HugoCPinto** [comment]
can I take this issue? =]

**Comment by raymag** [comment]
Sure, I'll assign you to it.
